spring.application.name=Backend
server.address=0.0.0.0
#192.168.29.120
#spring.datasource.url=jdbc:mysql://localhost:3307/pcanteen
server.port=8080
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:50050/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=iIEaNYACOOKzwkRVSQObvyxFjqcpaxDV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.properties.hibernate.format_sql=true


jwt.secret=JmGKSMo0dOLRd1CGd2CRm9oP8XcAmiQtONKBMva59b0=
jwt.expiration=86400000 

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true



# Email Config (Gmail Example)
>>>>>>> branch 'main' of https://github.com/Akanksha-999/PCanteenBackendNew
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sensophia012@gmail.com
spring.mail.password=qnli adbh phle rlsm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#logging:
 # level:
  #  org.springframework: INFO
   # com.pcanteen: DEBUG

























































































































